# Generated by Django 3.1.2 on 2020-10-11 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguyenThanhSon36User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('librarian', 'librarian'), ('student', 'student'), ('teacher', 'teacher')], max_length=40)),
                ('email', models.CharField(max_length=512, unique=True)),
                ('address', models.CharField(max_length=512)),
                ('phone', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NguyenThanhSon36Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='NguyenThanhSon36Ordered',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_list', models.CharField(max_length=512)),
                ('price', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NguyenThanhSon36Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_list', models.CharField(max_length=512)),
                ('price', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NguyenThanhSon36Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=512)),
                ('year', models.CharField(max_length=5)),
                ('company', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.nguyenthanhson36category')),
            ],
        ),
    ]
