# Generated by Django 3.1.2 on 2020-10-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguyenthanhson36category',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
