# Generated by Django 3.1.2 on 2020-10-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20201011_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguyenthanhson36books',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='nguyenthanhson36user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('librarian', 'librarian'), ('student/teacher', 'student/teacher')], max_length=40),
        ),
    ]
