# Generated by Django 3.1.2 on 2020-10-15 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20201013_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguyenthanhson36order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='nguyenthanhson36ordered',
            name='price',
        ),
    ]
