# Generated by Django 3.1.2 on 2020-10-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20201015_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguyenthanhson36books',
            name='max_stock',
            field=models.IntegerField(default=0),
        ),
    ]
