# Generated by Django 3.1.2 on 2020-10-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_nguyenthanhson36books_max_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguyenthanhson36user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
